Refactor
Star-Academy/Team3-Codes pull request #1
Opened 2020-08-03 07:43 UTC by kimianoorbakhsh

2020-08-03 08:14 UTC, Danyal0096 reviewed
راستیتش کد رو نتونستم بخونم چون سایز بزرگ مین اتون منو ترسوند و چشمامو خسته میکرد برنامه درایور نباید انقد طولانی باشه و خیلی از کارایی که کردید باید تو متد های خودشون نوشته میشد تو کلاس های مربوطه

2020-08-03 08:40 UTC, mahdimalverdi requested changes

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +    static Scanner scanner = new Scanner(System.in);
استفاده از این حجم از استاتیک کار درستی نیس
یک کلاس Possessor ایجاد کنید و کل فرآیندی که اینجا به صورت استاتیک نوشته شده رو درون اون کلاس انجام بدید

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
>      static HashMap<String, ArrayList<Integer>> tokens = new HashMap<>();
استاتیک بوددنش کار درستی نیس

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +    static final String NONE_SIGN_REGEX = "^(\\w*)";
این ها به یه کلاس تحت عنوان Regex Operators برده بشه و اونجا پابلیک استیتک باشه و بقیه جاها بهشون استناد بشه

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
>          int numberOfDocs = fillTheMap();
فقط یه شی از کلاس پراسسور ساخته بشه و اینجا تابع proccess کال بشه

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +    public static ArrayList<Integer> process(String input, int numberOfDocs) {
چرا تمام توابع پابلیک هستن؟
باید پرایوت باشن در صورت لزوم پابلیک بشن
نیازی هم نیس توابع استیتک باشن
خیلی با شی گرایی میونه خوبی نداره

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +        ArrayList<Integer> beforeMinus = Arithmetic.doOperation(Arithmetic.andAll(noneSignWords, tokens),
یه تابع تحت عنوان And درست بشه و مقادیر مورد نیاز بهش پاس داده بشه

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +        ArrayList<Integer> beforeMinus = Arithmetic.doOperation(Arithmetic.andAll(noneSignWords, tokens),
برای بعدها که می خواین دیباگ بکنید بهتره مقادیر خروجی توابع رو درون یه متغییر بریزید و بعد اون رو به تابعتون پاس بدید

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +        return Arithmetic.doOperation(beforeMinus, Arithmetic.orAll(wordsWithMinusSign, tokens),Operation.SUBTRACT);
یه تابع Substract ایجاد بشه و مقادیر مور نیاز بهش پاس داده بشه

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +                invertedIndex.makeChanges(FileReader.getFileContents("Docs\\" + p.getFileName().toString()), i);
آدرس فایل در یک متغییر ایجاد بشه تا کد خواناا تر بشه

2020-08-03 08:40 UTC, mahdimalverdi commented on Phase01-Search/Main.java
> +                invertedIndex.makeChanges(FileReader.getFileContents("Docs\\" + p.getFileName().toString()), i);
فایل کانتنتس رو داخل یه متغییر دیگه بریزید بعد به تابع پاس بدید

2020-08-03 08:52 UTC, ahmadsalimi commented on Phase01-Search/Main.java
>      public static int fillTheMap() {
<div dir="rtl">
بنظرم به جای این که این عملیات خوندن از فایل و درست کردن inverted index رو تو Main انجام بدین، بهتر بود یک کلاس می‌ساختین که با گرفتن آدرس فایل‌ها بره فایلا رو بخونه و یه Map بسازه بعنوان inverted index. حتی داخل اون کلاس هم احتمالا بهتر بود عملیات به چند کلاس (حالا خوندن از فایل که کلاس آماده داره، ولی در مراحل بعدیش، کلاس برای تمیزسازی (اگر لازم هست)، کلاس برای tokenize کردن و کلاس برای index کردن token ها می‌تونست وجود داشته باشه و اینطوری اصل Single Responsibility رو هم رعایت می‌کردید.)

</div>

2020-08-03 08:52 UTC, ahmadsalimi commented on Phase01-Search/Arithmetic.java
> +                .orElse(new ArrayList<>());
<div dir="rtl">
اینجا بنظرم برای خوانایی بیشتر بهتر بود اینجوری می‌نوشتین:
</div>
<br>

```java
return array.stream()
    .map(a -> tokens.get(a))
    .reduce((a, b) -> Arithmetic.doOperation(a, b, Operation.AND))
    .orElse(new ArrayList<>());
```

2020-08-03 08:52 UTC, ahmadsalimi commented on Phase01-Search/Arithmetic.java
> +                break;
<div dir="rtl">

کلا اکثر جاهایی که switch case می‌بینیم احتمالاً یا بهتره از polymorphism استفاده کنیم یا هم توابع جداگونه بزنیم براش.
<a href="https://www.c-sharpcorner.com/article/switch-statement-a-code-smell/">این لینک</a> رو بخونین دقیق‌تر گفته.

</div>

2020-08-03 08:52 UTC, ahmadsalimi commented on Phase01-Search/Main.java
> +    public static ArrayList<Integer> process(String input, int numberOfDocs) {
<div dir="rtl">

کل این تابع هم می‌تونست توی یک کلاس دیگه باشه، چون اینجا کلاس Main عملا تبدیل شده به God Class و همه کارا رو خودش داره می‌کنه، بهتره از کلاس وظیفه‌ی خاص خودش رو داشته باشه

</div>

2020-08-03 08:55 UTC, titansarus commented on Phase01-Search/Arithmetic.java
> +                if (arr1.size() == 0 || arr2.size() == 0)
برای مقایسه سایز 0 به نظرم isEmpty() استفاده بشه

2020-08-03 08:58 UTC, titansarus commented on Phase01-Search/Arithmetic.java
> +        switch (operation) {
تا جایی که می دونم، سوییچ کیس ها بهتره که همیشه دیفالت داشته باشن، مثلا برای وقتی که متغیر نال شد، یک حالت دیفالت (حتی اگه کاری انجام نمیده) وجود داشته باشه بهتره.

2020-08-03 09:02 UTC, titansarus commented on Phase01-Search/Main.java
>              DirectoryStream<Path> directoryStream = Files.newDirectoryStream(Paths.get("Docs"));
این دایرکتوری استریم در نهایت کلوز نشده. مشکل اجرایی پیدا نمی کنه برنامه ولی اگر یک کد بزرگ باشه، یکمی به پرفرمنس آسیب می زنه استریمی که استفاده نمیشه کلوز نشده باشه.

2020-08-03 09:42 UTC, kimianoorbakhsh commented on Phase01-Search/Arithmetic.java
> +                if (arr1.size() == 0 || arr2.size() == 0)
درسته، اصلاح میکنم، ممنون

2020-08-03 10:33 UTC, kimianoorbakhsh reviewed
نکات بیان شده بررسی و اصلاح شد، ممنون.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Arithmetic.java
> +                break;
اول توابع جداگونه زده بودیم، منتها چون خیلی توابع مشابه شده بودند تصمیم گرفتیم که از این روش استفاده کنیم که همه در یک تابع جمع شوند.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Arithmetic.java
> +                .orElse(new ArrayList<>());
بله اول همینطوری بود ولی چون ما تابع 
and 
رو کلا برداشتیم، به این صورت در اومد.
به نظرتون بهتره که 
and
اضافه بشه که مشکل 
switch case
هم حل بشه؟

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
> +    static Scanner scanner = new Scanner(System.in);
بله، ممنون اصلاح شد.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
>      static HashMap<String, ArrayList<Integer>> tokens = new HashMap<>();
این موضوع نیز با اضافه کردن کلاس جدید به عنوان 
processor
اصلاح شد، ممنون.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
> +    static final String NONE_SIGN_REGEX = "^(\\w*)";
اصلاح شد.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
>          int numberOfDocs = fillTheMap();
با ساخته شدن کلاس جدید، این موضوع هم اعمال شد، ممنون.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
> +    public static ArrayList<Integer> process(String input, int numberOfDocs) {
اصلاح شد، توابع درون کلاسی رو پرایوت کردم.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
> +    public static ArrayList<Integer> process(String input, int numberOfDocs) {
بله درسته، کلاس جدیدی ساختم و توابع دیگر را به آن انتقال دادم .، ممنون

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
> +        ArrayList<Integer> beforeMinus = Arithmetic.doOperation(Arithmetic.andAll(noneSignWords, tokens),
بله، اول به همین صورت بود ولی بعدش فکر کردیم شاید بهتر باشه اینجوری تغییر بدیم.. درسته من تغییرش میدم به حالت قبل

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
>      public static int fillTheMap() {
بله دو کلاس جدید ساختم که این مشکلات رو برطرف میکنه، ممنون.

2020-08-03 10:33 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
> +                invertedIndex.makeChanges(FileReader.getFileContents("Docs\\" + p.getFileName().toString()), i);
اصلاح شد ، ممنون.

2020-08-03 10:42 UTC, kimianoorbakhsh reviewed
تغییرات لازم اعمال شد.

2020-08-03 11:06 UTC, Parsa2820 commented on Phase01-Search/Main.java
> +    static Scanner scanner = new Scanner(System.in);
<p dir="rtl">
متغییر scanner فقط تو همین تابع استفاده شده. فکر کنم لوکال باشه بهتره.
</p>

2020-08-03 12:14 UTC, ahmadsalimi commented on Phase01-Search/Arithmetic.java
> +                .orElse(new ArrayList<>());
<div dir="rtl">

آره کلا که اگر توابع به خصوص رو جایگزین این switch case کنین خیلی بهتر میشه (کلا اگر می‌بینی که duplicate code داره به وجود میاد میشه از polymorphism کمک گرفت)

به جز این هم نکته‌ای که داشتم این بود که خط ۳۱ خیلی طولانی شده و وقتی اینجوری پشت سر هم روی خروجی یه تابع، یه تابع دیگه کال میشه، بهتره هر کدومش رو تو یک خط جدا بذارید (با یه indent بیشتر، همونطور که تو کامنت بالا نشون دادم)

</div>

2020-08-03 12:17 UTC, ahmadsalimi commented on Phase01-Search/Arithmetic.java
> +                break;
<div dir="rtl">

پیشنهاد من اینه که یک کلاس `abstract` داشته باشیم که یک تابع پابلیک داشته باشه که بخش های مشترک عملیات ها رو انجام میده، و اون نقطه ای که سه عملیات متفاوت هستن با هم رو تو یک تابع `protected abstract` بذاریم که به ازای هر عملیات، یک ارث بری از این کلاس abstract داشته باشیم و صرفا اون تابع `protected abstract` رو پیاده سازی کرده باشن.

</div>

2020-08-03 13:20 UTC, ahmadsalimi approved these changes

2020-08-03 15:58 UTC, kimianoorbakhsh commented on Phase01-Search/Main.java
> +    static Scanner scanner = new Scanner(System.in);
درسته ممنون.

2020-08-03 20:52 UTC, mahdimalverdi approved these changes

2020-08-03 20:57 UTC, AlirezaT99 approved these changes
بجز همون 
isEmpty
بجای
size() == 0
که دوستان اشاره کرده بودن چیزی نیس که اصلاح نشده باشه.. موفق باشید

2020-08-04 06:09 UTC, titansarus approved these changes

2020-08-04 06:21 UTC, sabaebrahimi reviewed
خیلی خوب بود فقط اینکه 
1. بنظرم یه پیغام بدید به کاربر که بدونه کی باید کلمه مورد نظرشو برای سرچ وارد کنه
2. اگر 
arraylist 
ای که توش id
داکیومنت ها رو نگهداری می کنید از جنس استرینگ می بود و نام فایل ها رو توش نگهداری می کردید تا بشه راحت تر بهشون مراجعه کرد خیلی بهتر میشد. 
موفق باشید

2020-08-04 06:43 UTC, sabaebrahimi approved these changes

2020-08-04 06:44 UTC, merged