Unit test
Star-Academy/Team3-Codes pull request #2
Opened 2020-08-09 11:44 UTC by mahlashrifi

2020-08-09 12:52 UTC, titansarus commented on Search/maven/src/test/java/Search/ProcessorTest.java
> +        int numberOfDocs = processor.fillTheMap();
به نظرم این جا می شد از
mockito
استفاده کرد
برای
mock
کردن رفتار
FileReader
که نیازی به خوندن واقعی اون از روی فایل نباشه که اگر پیاده سازیش عوض بشه، باعث فیل شدن تست های پروسسور نشه.
هر چند میشه هم استفاده نکرد ولی استفاده کردن ازش بهتره. نکته دیگه ای به نظرم نرسید. موفق باشید.

2020-08-09 12:52 UTC, titansarus approved these changes

2020-08-09 14:15 UTC, MJavadHzr approved these changes
نکته ی خاصی به نظرم نرسید فقط همون اگر بتونید وابستگی تست پروسسر رو به فایل ریدر از بین ببرید عالی 
.میشه، ولی بازم در کل تست ها به خوبی نوشته شده، موفق باشید .

پاسخ : اصلاح شد . ممنون .

2020-08-09 16:30 UTC, mahdimalverdi requested changes

2020-08-09 16:30 UTC, mahdimalverdi commented on Search/maven/src/main/java/Search/FileReader.java
>          while (input.hasNext())
چرا کلا از این نوع ترای کچ استفاده می کنید؟
خب بزارید بیاد تا بالا خطا
اینجا اگه خطا بخوره بعدش خطای نال نی خوره اینجا!

2020-08-09 16:30 UTC, mahdimalverdi commented on Search/maven/src/main/java/Search/RegexOperator.java
> +    public static ArrayList<String> assortTheWords(String input, String regex, int groupOfWordInRegex) {
چرا استاتیک 🤔🤔

2020-08-09 17:22 UTC, ahmadsalimi commented on Search/maven/src/main/java/Search/InvertedIndex.java
>          this.dictMap = dictMap;
<div dir="rtl">

اینجا چه لزومی داره `HashMap` از بیرون پاس داده بشه؟ خب تو همین کلاس `new` بشه و یه `getter` براش بذارید مشکلش چیه؟

</div>

2020-08-09 17:22 UTC, ahmadsalimi commented on Search/maven/src/test/java/Search/ProcessorTest.java
> +        ArrayList<Integer> actualResult = processor.process("sky -blue", numberOfDocs);
<div dir="rtl">

اینجا به نظر می‌رسه تمام حالت ها چک نشده، مثلا  prefix عه + بعنوان ورودی داده نشده و احتمالا کل کد رو کاور نمی‌کنه.

</div>

2020-08-10 06:22 UTC, mahlashrifi commented on Search/maven/src/main/java/Search/FileReader.java
>          while (input.hasNext())
<div dir="rtl">
منظورتون اینه که کلا اکسپشن رو هندل نکنیم ؟ توی تمام متدها throw کنیم ؟
</div>

2020-08-10 06:22 UTC, mahlashrifi commented on Search/maven/src/test/java/Search/ProcessorTest.java
> +        ArrayList<Integer> actualResult = processor.process("sky -blue", numberOfDocs);
اصلاح شد .

2020-08-10 12:26 UTC, mahlashrifi commented on Search/maven/src/main/java/Search/InvertedIndex.java
>          this.dictMap = dictMap;
<div dir="rtl">

مشکلی که نداره . منتها این `HashMap` فیلد کلاس `Processor`  هست . همونجا `new` میشه .

</div>

2020-08-10 12:40 UTC, mahlashrifi commented on Search/maven/src/test/java/Search/ProcessorTest.java
> +        int numberOfDocs = processor.fillTheMap();
<div dir="rtl">

mock  شد و مشکل برطرف شد . ممنونم .

</div>

2020-08-10 12:44 UTC, mahlashrifi commented on Search/maven/src/main/java/Search/RegexOperator.java
> +    public static ArrayList<String> assortTheWords(String input, String regex, int groupOfWordInRegex) {
<div dir="rtl">

اصلاح شد .

</div>

2020-08-11 05:34 UTC, sabaebrahimi approved these changes

2020-08-11 06:28 UTC, mahdimalverdi commented on Search/maven/src/main/java/Search/FileReader.java
>          while (input.hasNext())
آره تقریبا

2020-08-11 08:42 UTC, ahmadsalimi commented on Search/maven/src/main/java/Search/InvertedIndex.java
>          this.dictMap = dictMap;
<div dir="rtl>

منم دقیقا حرفم اینه که کلا هش‌مپ رو ببر تو `InverterIndex` و هر جا تو `Processor` لازمش داشتی، از `getter`ی که تو `InvertedIndex` می‌ذاری استفاده کن.

</div

2020-08-11 08:59 UTC, mahdimalverdi approved these changes

2020-08-11 10:30 UTC, kimianoorbakhsh commented
phase 3 done

2020-08-11 10:30 UTC, merged