Phase05
Star-Academy/Team3-Codes pull request #4
Opened 2020-08-16 06:11 UTC by kimianoorbakhsh

close Star-Academy/codestar-intern-issues/issues/58

2020-08-16 06:40 UTC, sabaebrahimi commented on Phase05/Search/Search/Model/InvertedIndex.cs
> +        public void updateTheMap(string docContent, int docID)
توابع باید 
pascal case باشند

2020-08-16 06:42 UTC, sabaebrahimi commented on Phase05/Search/Search/Model/Processor.cs
> +        And and = new And();
اینجاها var
اگر می ذاشتید یه مقدار به خوانایی کمک می کرد

2020-08-16 06:44 UTC, mahlashrifi commented on Phase05/Search/Search/Model/InvertedIndex.cs
> +        public void updateTheMap(string docContent, int docID)
<div dir="rtl">
درسته کاملا . ممنونم . اصلاح شد .
</div>

2020-08-16 06:45 UTC, sabaebrahimi commented on Phase05/Search/Search/Model/Processor.cs
> +    public class Processor
fill the map بنظرم در این کلاس بیاید و 
رو کلا خارج کنید... چون کاربریش فرق داره. یجورایی مربوط به پر کردن 
inverted index 
با استفاده از فایل یا کلا سورسمون میشه. 
اما مثلا تابع process
کلا کاربری جدایی داره و مربوط به پردازش علامتاست.

2020-08-16 06:47 UTC, sabaebrahimi commented on Phase05/Search/Search/Program.cs
> +            var reader = new FileReader("Resources");
میشد که 
"Resources"
رو از جنس کانست تعریف کنید

2020-08-16 06:50 UTC, mahlashrifi commented on Phase05/Search/Search/Model/Processor.cs
> +        And and = new And();
<div dir="rtl">
اصلاح شد . ممنون .</div>

2020-08-16 06:58 UTC, sabaebrahimi commented on Phase05/Search/Search.Test/ModelTest/InvertedIndexTest.cs
> +        public void initMap()
بنظرم این تابع با توجه به این که درستی یا نادرستی چیزی رو تست نمی کنه، بالاش 
[Fact]
رو نذارید. از اونجایی که برای پر کردن 
map
هست، میشه داخل 
UpdateTheMapTest
صداش بکنید یا داخل سازنده ی 
InvertedIndexTest
تا جز تست ها حساب نشه

2020-08-16 07:01 UTC, sabaebrahimi commented on Phase05/Search/Search.Test/UtilsTest/FileReaderTest.cs
> +            Assert.Equal(reader.MoveNext(),true);
اینجا قشنگ تر می شد اگر به جای 
Assert.Equal 
می ذاشتید 
Assert.True(reader.MoveNext())

2020-08-16 07:04 UTC, mahlashrifi commented on Phase05/Search/Search.Test/ModelTest/InvertedIndexTest.cs
> +        public void initMap()
<div dir="rtl">
حل شد . مرسی .
</div>

2020-08-16 07:05 UTC, mahlashrifi commented on Phase05/Search/Search.Test/UtilsTest/FileReaderTest.cs
> +            Assert.Equal(reader.MoveNext(),true);
<div dir="rtl">
قشنگ تر شد :)
</div>

2020-08-16 07:59 UTC, sabaebrahimi commented on Phase05/Search/Search.Test/UtilsTest/LogicalOperationTest.cs
> +          initTokens();
میشد که متد 
initTokens
در سازنده ی 
LogicalOperationTest
قرار داده بشه تا قبل از هر تست انجام بشه و دیگه لازم نباشه هر بار صداش بزنید.

2020-08-16 08:16 UTC, mahdimalverdi requested changes

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search.Test/UtilsTest/OperationTests.cs
> +        protected abstract void init();
اینجا چرا Fact هست؟

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search/Model/RegexOperator.cs
> +                 foreach(Match m in matches)
```CSharp
if(matches == null)
{
 throw new NullArgumentExcepyion();
}

return matches.Select(m => m.Groups[2].Value).ToList();
```

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search/Program.cs
> +            Console.WriteLine("Enter the string of words which you want to search .");
کلا هر چی استریک و عدد دارید به کانست توی کلاس تبدیل کنید

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search/Program.cs
> +                Console.Write(integer + " ");
```CSharp
Console.Write($"{integer} ")
```

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search/Utils/And.cs
> +            HashSet<int> temp = new HashSet<int>(set1);
```CSharp
return set1.Intersect(set2).ToHashSet()
```

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search/Utils/Or.cs
> +            HashSet<int> temp = new HashSet<int>(set1);
```CShasp
set1.Union(set2).ToHashSet();
```

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search/Utils/Subtract.cs
> +            HashSet<int> temp = new HashSet<int>(set1);
set1.Except(set2).ToHashSet()

2020-08-16 08:16 UTC, mahdimalverdi commented on Phase05/Search/Search/Utils/logicalOperation.cs
> +            if(words.Where(w => tokens.ContainsKey(w)).FirstOrDefault() == null)
```CSharp
words.FirstOrDefault(w => tokens.ContainsKey(w))
```

2020-08-16 08:36 UTC, titansarus commented on Phase05/Search/Search/Program.cs
> +            foreach (int integer in processor.process(Console.ReadLine(), numberOfDocs))
این
int integer
رو میشه
var integer
نوشت.

2020-08-16 08:37 UTC, titansarus commented on Phase05/Search/Search/Program.cs
> +using Search.Model;
فکر کنم
using System.Linq
در کد این بخش استفاده نشده و میشه حذفش کرد.

2020-08-16 08:40 UTC, titansarus commented on Phase05/Search/Search/Utils/FileReader.cs
> +            return this.files.MoveNext();
این
this
ها رو میشه برداشت.
چون متغیر همنام با
files
نیست خودش تشخیص میده.

2020-08-16 08:43 UTC, titansarus commented on Phase05/Search/Search/Utils/IOperation.cs
> +
میشه به جای
HashSet
نوشت
ISet
که
Dependency Inversion
بیش تر رعایت بشه.
چون قابلیت های کلیدی مجموعه مثل اشتراک و اجتماع و... رو
ISet
داره.

2020-08-16 08:49 UTC, titansarus commented on Phase05/Search/Search/Model/RegexOperator.cs
> +         {
این پارامتر
int groupOfWordInRegex
به نظرم داخل کد استفاده نشده بود.

فکر کنم
m.Groups[groudOfWordInRegex]

قرار بوده باشه که الان فقط عدد 2 هست در اون جا.

2020-08-16 08:50 UTC, titansarus commented on Phase05/Search/Search/Model/Processor.cs
> +    public int fillTheMap() {
اسم متودها باید با حرف بزرگ شروع بشه.

2020-08-16 08:56 UTC, titansarus commented on Phase05/Search/Search/Model/InvertedIndex.cs
> +        public void updateTheMap(string docContent, int docID)
یک نکته ای در مورد
naming convetion
در سایت مایکروسافت نوشته که تقریبا تمامی مخفف ها مثل
ID

فقط حرف اولشون بزرگ نوشته میشه مثل سایر کلمات.

یعنی این جا هم  باید
docId

باشه. تنها استثنایی که نوشته بود فکر کنم

IO
بود مثلا داخل
IOStream
که گفته بود این مخفف **دو** حرفیه که هر دو مخفف یک کلمه مجزا هستن و برای همین هر دو بزرگ نوشته می شن.

2020-08-16 10:08 UTC, mahlashrifi commented on Phase05/Search/Search/Program.cs
> +            foreach (int integer in processor.process(Console.ReadLine(), numberOfDocs))
<div dir="rtl">
 ممنونم . اصلاح شد .
</div>

2020-08-16 10:10 UTC, mahlashrifi commented on Phase05/Search/Search/Utils/FileReader.cs
> +            return this.files.MoveNext();
<div dir="rtl">
حل شد ممنون.
</div>

2020-08-16 10:12 UTC, mahlashrifi commented on Phase05/Search/Search/Model/RegexOperator.cs
> +         {
<div dir="rtl">
در اینجا 2 بوده . اما برای اینکه متد برای همه ی regex ها قابل استفاده باشه . بهش نیاز هست . 
</div>

2020-08-16 10:13 UTC, mahlashrifi commented on Phase05/Search/Search/Utils/And.cs
> +            HashSet<int> temp = new HashSet<int>(set1);
<div dir="rtl">
اعمال شد .
</div>

2020-08-16 10:14 UTC, mahlashrifi commented on Phase05/Search/Search/Program.cs
> +                Console.Write(integer + " ");
<div dir="rtl">
اعمال شد . ممنون .
</div>

2020-08-16 10:15 UTC, mahlashrifi commented on Phase05/Search/Search/Program.cs
> +            var reader = new FileReader("Resources");
<div dir="rtl">
const  شد .
</div>

2020-08-16 10:17 UTC, mahlashrifi commented on Phase05/Search/Search.Test/UtilsTest/OperationTests.cs
> +        protected abstract void init();
حل شد .

2020-08-16 10:19 UTC, mahlashrifi commented on Phase05/Search/Search/Utils/logicalOperation.cs
> +            if(words.Where(w => tokens.ContainsKey(w)).FirstOrDefault() == null)
<div dir="rtl">
ممنون . اصلاح شد .
</div>

2020-08-16 10:25 UTC, mahlashrifi commented on Phase05/Search/Search/Model/Processor.cs
> +    public class Processor
<div dir="rtl">
tokens فیلد این کلاس هست . و همینجا ساخته میشه ، پر میشه ، و درنهایت لیست مکان های کلمات خواسته شده ازش استخراج میشه . 
به همین خاطر فکر می کنیم جاش مناسب باشه :) . مرسی بابت کامنت .
</div>

2020-08-16 10:26 UTC, mahlashrifi commented on Phase05/Search/Search/Model/Processor.cs
> +    public int fillTheMap() {
<div dir="rtl">
ممنون . اصلاح شد .
</div>

2020-08-16 10:30 UTC, mahdimalverdi approved these changes

2020-08-16 10:37 UTC, Danyal0096 approved these changes
دیر رسیدم همرو ریزالو کردید :)) و خب خوب بود موفق باشید چیز دیگه ای ندیدم اضافه کنم

2020-08-16 11:17 UTC, titansarus approved these changes
به جز همون ایرادهایی که گفته شد و اصلاح کردید، همه چی خوب بود. موفق باشید.

2020-08-16 12:21 UTC, sabaebrahimi approved these changes

2020-08-17 04:35 UTC, alrz1999 approved these changes

2020-08-17 06:38 UTC, ahmadsalimi approved these changes

2020-08-17 06:38 UTC, ahmadsalimi commented on Phase05/Search/Search/Utils/FileReader.cs
> +        }
Use Expression body for single-line methods:
```CSharp
public bool MoveNext() => files.MoveNext();
```

2020-08-17 09:20 UTC, merged