Phase08
Star-Academy/Team3-Codes pull request #6
Opened 2020-08-24 11:51 UTC by mahlashrifi

close  Star-Academy/codestar-intern-issues/issues/82

2020-08-24 13:08 UTC, titansarus commented on SearchNest/SearchNest/View/ConsolePrinter.cs
> +            foreach (var doc in Docss)
متغیرهای درونی توابع با حروف کوچیک باید نوشته بشن.
Docss -> docs

2020-08-24 13:09 UTC, titansarus commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +            var wordsThatMatch = new List<string>();
خروجی تابع از نوع
IEnumerable
باشه بهتره.

2020-08-24 13:10 UTC, titansarus commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +{
اسم
namespace
با پوشه ای که داخلشه هماهنگی نداره. بهتره که هماهنگ باشه.
SearchNest.Utils

2020-08-24 13:12 UTC, titansarus commented on SearchNest/SearchNest/Utils/Processor.cs
> +        {
اسم متود بهتره با حرف بزرگ شروع بشه.

2020-08-24 13:12 UTC, titansarus commented on SearchNest/SearchNest/Utils/Processor.cs
> +            int i = 0;
میشه از
var
استفاده کرد.

2020-08-24 13:15 UTC, titansarus commented on SearchNest/SearchNest/Utils/Reader/FileReader.cs
> +        }
از اون جایی که
files
از جنس
IEnumerable<string>
عه به نظرم نیازی به نوشتن
ToString()
نیست.

2020-08-24 13:17 UTC, titansarus commented on SearchNest/SearchNest/Utils/Nest/ResponseValidator.cs
> +        {
اسم متود با حروف بزرگ باشه بهتره.

2020-08-24 13:21 UTC, titansarus commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +                                                   ))
به جای این
Count()
آخر به نظرم از
property
Length
استفاده بشه بهتره.
ظاهرا
Length
تضمین شده
O(1)
عه ولی
Count
ممکنه در بعضی حالات
O(N)
عمل کنه و این جا هم
Length
جوابگوعه.

`noneSignWords.Split(" ").Length`

2020-08-24 14:13 UTC, mostmand commented on SearchNest/.vscode/tasks.json
> +{
.vscode
رو بذارید توی
.gitignore

2020-08-24 14:13 UTC, mostmand commented on SearchNest/SearchNest/Program.cs
> +                var responseOfSearchQuery = processor.doProcess(Console.ReadLine(), client, "documents");
تابع
doProcess
چرا
PascalCase
نیست؟

2020-08-24 14:13 UTC, mostmand commented on SearchNest/SearchNest/Program.cs
> +                var responseOfSearchQuery = processor.doProcess(Console.ReadLine(), client, "documents");
هم‌‌چنین تابع
handleException

2020-08-24 14:13 UTC, mostmand commented on SearchNest/SearchNest/Utils/Processor.cs
> +            while (reader.MoveNext())
چرا از
foreach
استفاده نمی‌کنید؟

2020-08-24 14:13 UTC, mostmand commented on SearchNest/SearchNest/Utils/Processor.cs
> +            while (reader.MoveNext())
البته احتمالا کدتون یه تغییراتی باید بکنه که بتونید از
foreach
استفاده کنید ولی این
MoveNext
و اینا خوانایی کد رو میاره پایین

2020-08-24 14:13 UTC, mostmand commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +                                                    .MinimumShouldMatch(noneSignWords.Split(" ").Count())
می تونید از
operator and
استفاده کنید به جای این 
MinimumShouldMatch

2020-08-24 14:13 UTC, mostmand commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +                                                    .MinimumShouldMatch(1)))
به نظرم این جا
MinimumShouldMatch
تأثیری نداره چون دیفالت هم رفتارش همین طوره

2020-08-24 14:13 UTC, mostmand commented on SearchNest/SearchNest/Utils/Nest/ResponseValidator.cs
> +            if (!response.IsValid)
بیش از حد ساده است این متد برای مثال
validator
تیم‌های 7 و 8 رو دیدم خوب بودن یه نگاهی بندازید به اونا

2020-08-25 05:37 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/View/ConsolePrinter.cs
> +            foreach (var doc in Docss)
ممنونم، اصلاح شد

2020-08-25 05:38 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +            var wordsThatMatch = new List<string>();
ممنون بابت کامنت، فقط من خوبی این کار رو متوجه نمیشم، چرا بهتره؟

2020-08-25 05:40 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +{
مرسی ، اصلاح کردمش

2020-08-25 05:41 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Processor.cs
> +        {
ممنونم، اصلاح شد

2020-08-25 05:42 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Reader/FileReader.cs
> +        }
فک کنم
files.current
چون از جنس استرینگ نبود مشکل پیش می آورد و برای همین اینطوری نوشتیمش.

2020-08-25 05:43 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Nest/ResponseValidator.cs
> +        {
ممنون، اصلاح شد.

2020-08-25 05:59 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Reader/FileReader.cs
> +        }
درسته، ممنونم

2020-08-25 06:01 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +                                                   ))
خیلی ممنون، اصلاح شد

2020-08-25 06:07 UTC, kimianoorbakhsh commented on SearchNest/.vscode/tasks.json
> +{
<div dir="rtl">خیلی از فایل هاش ایگنور میشن، منتها چون از خود 
gitignore.io
 کپی کرده بودیم، یه سه چهار تا فایلو زده لود که ایگنور نکنه، ولی الان اونارم برداشتم، ممنون</div>

2020-08-25 06:07 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Program.cs
> +                var responseOfSearchQuery = processor.doProcess(Console.ReadLine(), client, "documents");
بله اونارو اصلاح کردیم، ممنونم.

2020-08-25 06:10 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Processor.cs
> +            while (reader.MoveNext())
<div dir="rtl">اینجا ما چون نمیدونستیم که چند تا doc داریم، اومدیم reader رو طوری تنظیم کردیم که هر بار یه فایل بخونه. </div>

2020-08-25 06:13 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +                                                    .MinimumShouldMatch(noneSignWords.Split(" ").Count())
بله درسته، ممنون

2020-08-25 06:13 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +                                                    .MinimumShouldMatch(1)))
ممنون، برداشتیم.

2020-08-25 07:10 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Nest/ResponseValidator.cs
> +            if (!response.IsValid)
بله کد ها را دیدیم و اصلاح کردیم ،  ممنونم

2020-08-25 07:40 UTC, mostmand commented on SearchNest/SearchNest/Utils/Processor.cs
> +            while (reader.MoveNext())
درسته ولی می‌تونید از
yield return
استفاده کنید
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/yield

2020-08-25 07:42 UTC, mostmand commented
این نکاتی که
GithubActions
توی
FilesChanged
پیشنهاد داده رو هم یه نگاه بندازید

2020-08-25 07:42 UTC, mostmand approved these changes

2020-08-25 07:47 UTC, titansarus commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +            var wordsThatMatch = new List<string>();
چون
IEnumerable
اینترفیس پایه ای تری از لیسته و لیست هم خودش از اون استفاده می کنه.
بعد هر چه قدر کلا
Dependency
ها به اینترفیس های پایه ای تر باشن بهتره.
یعنی طبق
Dependency Inversion
اگر وابستگی ها به اینترفیس ها باشه، بهتر از اینه که به پیاده سازی هایی از اون اینترفیس ها باشه.
مثلا لیست خودش
IEnumerable
رو پیاده سازی می کنه و این جا هم فراتر از قابلیت های
IEnumerable
به قابلیت بیش تری نیاز نیست که مثلا فقط در لیست باشه و مثلا در آرایه نباشه.

هر چند این جا شاید این موضوع خیلی خودش رو نشون نده ولی عادت کردن به این که تا جایی که ممکنه بیش تر از چیزی که برنامه نیاز داره رو براش مشخص نکنیم، بعدا برای کلاس هایی که خودمون می نویسم هم کمک می کنه.

مثلا یک جا داریم از هش ست استفاده می کنیم ولی به جز قابلیت
foreach
خوردن، از هیچ ویژگی اختصاصی هش ست استفاده نمی کنیم. این جا بهتره که
IEnumerable
باشه که اگه مثلا یک پیاده سازی دیگه هم با لیست انجام دادیم، خود تابع نیازی به تغییر نباشه. ولی جایی که واقعا داریم از یکسری توابع خاص هش ست استفاده می کنیم و یا دلایلی سر پرفرمنس وجود داره، اون جا واقعا باید ذکر بشه که فقط مثلا هش ست و نه 
IEnumerable
های دیگه.

2020-08-25 07:52 UTC, titansarus commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +            var wordsThatMatch = new List<string>();
البته این جا واقعا شاید این کار خیلی اهمیت نداشته باشه ولی باعث میشه که آدم عادت بکنه در کدها و کلاس های پیچیده ای که در آینده خواهیم نوشت هم این اصول رو رعایت کنه. مثلا یک اینترفیس
IReader
دارید و مثلا
JsonReader , WebReader , CsvReader
همگی اون رو ایمپلمنت کردن. در قسمت های دیگه برنامه که فقط به عملکرد خوندن فایل متکی هستن و خروجی رو می خوان، بهتره که مستقیما فقط
IReader
استفاده بشه و بعدا بنا به نیاز مثلا در مین پروژه
JsonReader
یا
WebReader
به اون پاس داده بشه
ولی اگه بیایم داخل کلاس هایی که از این استفاده می کنن، دقیقا مشخص کنیم که با جیسون ریدر فقط کار کنه، بعد مجبور میشیم برای یک کار ساده که وابستگیش فقط به عملیات خوندن و نوشتن بوده و واقعا براش نوع فایل مهم نبوده، سه تا تابع مختلف تعریف کنیم.

2020-08-25 07:52 UTC, titansarus approved these changes

2020-08-25 09:47 UTC, mahlashrifi commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +            var wordsThatMatch = new List<string>();
<div dir="rtl">جایی برای استفاده از string.Join فکر میکردیم List میگیره . و برای جلوگیری از cast دوباره این کار روکردیم . ولی چک کردم . گویا IEnumerable میگیره . و اصلاح شد . مرسی از توضیحات 🙏🏻🙏🏻 </div>

2020-08-25 12:21 UTC, ahmadsalimi requested changes

2020-08-25 12:21 UTC, ahmadsalimi commented on SearchNest/SearchNest/Program.cs
> +            connectionSettings.EnableDebugMode();
```CSharp
var connectionSettings = new ConnectionSettings(uri)
    .EnableDebugMode();
```

2020-08-25 12:21 UTC, ahmadsalimi commented on SearchNest/SearchNest/Utils/Nest/IndexHandler.cs
> +        ElasticClient client;
Use accessibility modifiers (maybe private readonly)

2020-08-26 05:19 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Program.cs
> +            connectionSettings.EnableDebugMode();
اصلاحش کردم، ممنونم

2020-08-26 05:20 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Nest/IndexHandler.cs
> +        ElasticClient client;
درسته، ممنونم

2020-08-26 05:22 UTC, ahmadsalimi approved these changes

2020-08-26 10:52 UTC, mahdimalverdi requested changes
یه سری خطای دیگه هم هست از فاز 5 اصلاح کنید هی توی پول ریکوئست هاتون نیاد

2020-08-26 10:52 UTC, mahdimalverdi commented on SearchNest/SearchNest/Program.cs
> +            // indexHandler.CreateMapping();
کامنت اضافه پاک بشه

2020-08-26 10:52 UTC, mahdimalverdi commented on SearchNest/SearchNest/Utils/Nest/IndexHandler.cs
> +                                .Analyzer("whitespace")
استرینگ ها تبدیل به متغیر کانست بشن تو کلاس

2020-08-26 10:52 UTC, mahdimalverdi commented on SearchNest/SearchNest/Utils/Nest/IndexHandler.cs
> +            ResponseValidator.handleValidation(client.Bulk(bulkDescriptor),"Bulking docs");
اینجا هم استرینگ نبشاه

2020-08-26 10:52 UTC, mahdimalverdi commented on SearchNest/SearchNest/Utils/Processor.cs
> +            var wordsWithPlusSign = string.Join(" ",RegexOperator.AssortTheWords(input, PLUS_REGEX, 2));
عدد ها و اون استرینگ اسپس به کانست تبدیل بشن

2020-08-26 10:52 UTC, mahdimalverdi commented on phase08/NestTest/Model/IndexHandler.cs
> +            var index = "people";
این چه وضعیه؟
بشکونید به تابع های کوچک تر
استرینگ ها و عدد ها هم کانست بشن

2020-08-26 10:52 UTC, mahdimalverdi commented on phase08/NestTest/Program.cs
> +            // var reader = new JsonReader();
کامنت ها پاک بشن

2020-08-29 07:32 UTC, mahlashrifi commented on phase08/NestTest/Program.cs
> +            // var reader = new JsonReader();
ممنون . اصلاح شد .

2020-08-29 07:48 UTC, mahlashrifi commented on SearchNest/SearchNest/Utils/Nest/IndexHandler.cs
> +            ResponseValidator.handleValidation(client.Bulk(bulkDescriptor),"Bulking docs");
اعمال شد

2020-08-29 07:49 UTC, mahlashrifi commented on SearchNest/SearchNest/Utils/Nest/IndexHandler.cs
> +            ResponseValidator.handleValidation(client.Bulk(bulkDescriptor),"Bulking docs");
اعمال شد .

2020-09-01 05:52 UTC, mahlashrifi commented on SearchNest/SearchNest/Utils/Nest/IndexHandler.cs
> +                                .Analyzer("whitespace")
ممنون اصلاح شد .

2020-09-01 09:47 UTC, mahdimalverdi requested changes

2020-09-01 09:47 UTC, mahdimalverdi commented on phase08/NestTest/Program.cs
> +            // var reader = new JsonReader();
اصلاح نشده!

2020-09-01 09:47 UTC, mahdimalverdi commented on phase08/NestTest/Model/Query.cs
> +                        Field = "about",
کانست بشن تمام استرینگ ها

2020-09-01 09:47 UTC, mahdimalverdi commented on phase08/NestTest/Model/IndexHandler.cs
> +namespace NestTest
این کلاس اگه استفاده نمیشه پاک بشه

2020-09-01 09:47 UTC, mahdimalverdi commented on SearchNest/SearchNest/View/ConsolePrinter.cs
> +            var docs = response.Documents.OrderByDescending(s => s.Id).ToList();
```CSharp
var line = string.Join(' ', docs.Select(d => d.Name));
Console.Write(line);
```

2020-09-01 09:47 UTC, mahdimalverdi commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +                    wordsThatMatch.Add(m.Groups[groupOfWordInRegex].Value);
return matches?.Select(m.Groups[groupOfWordInRegex].Value)?.ToList() : new List<string>();

2020-09-01 09:47 UTC, mahdimalverdi commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +            var response = client.Search<Document>(s => s
بشکنه

2020-09-02 05:55 UTC, kimianoorbakhsh commented on phase08/NestTest/Model/Query.cs
> +                        Field = "about",
جالبه، ما اصن همچین کلاسی توی پکیج 
model
مون نداریم، ولی چشم همه رو کانست میکنم.

2020-09-02 05:58 UTC, kimianoorbakhsh commented on phase08/NestTest/Model/Query.cs
> +                        Field = "about",
چشم، البته اینا همه برای بخش تمرینی 
nest 
 ما هستن، پروژه اصلیمون توی قسمت 
SearchNest 
هستش و چون اینا تمرینی بودن اصن وقت برای ریفکتور و اینا نذاشتیم. صصرفا اینا رو به گیت اضافه کردیم که یه جا داشته باشیمشون.

2020-09-02 06:05 UTC, kimianoorbakhsh commented on phase08/NestTest/Model/IndexHandler.cs
> +namespace NestTest
استفاده میشه، ولی برای دوبار نساختن mapping کامنتش کرد بودیم که الان برداشتیم.

2020-09-02 06:07 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/View/ConsolePrinter.cs
> +            var docs = response.Documents.OrderByDescending(s => s.Id).ToList();
اصلاح شد، ممنون

2020-09-02 06:09 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/RegexOperator.cs
> +                    wordsThatMatch.Add(m.Groups[groupOfWordInRegex].Value);
راستش من اینو خیلی خوب متوجه نمیشه، کدشم میزنم ارورو میده بهم

2020-09-02 06:11 UTC, kimianoorbakhsh commented on SearchNest/SearchNest/Utils/Nest/SearchQuery.cs
> +            var response = client.Search<Document>(s => s
اینجا چون ما 
bool query 
داریم، 
گفتیم اگه همه یک جا باشن خواناییش بیشتر میشه

2020-09-05 12:29 UTC, mahdimalverdi approved these changes

2020-09-06 05:16 UTC, merged