Phase09
Star-Academy/Team3-Codes pull request #8
Opened 2020-09-02 11:19 UTC by kimianoorbakhsh

close Star-Academy/codestar-intern-issues/issues/87

2020-09-03 18:56 UTC, ahmadsalimi approved these changes
<div dir="rtl">
به وارنینگ‌های یونیت تست‌هاتون توجه کنین. الان جای expected و actual برعکسه.
</div>

2020-09-05 05:48 UTC, Parsa2820 approved these changes
خوب بود. خسته نباشید. فقط یه سری جاها نمیشد کامنت گذاشت. اگه کسی میدونه چرا بگه 😁
![image](https://user-images.githubusercontent.com/39219981/92298656-8e35a280-ef60-11ea-8dde-109dcd072106.png)
اینجا مثلا یه اینتر میخواست

2020-09-05 05:49 UTC, hassanzaker reviewed
کلا یسری فایل اضافه که مربوط به این فاز نیست اینجا وجود داره که باید به گیت‌ایگنور اضافه بشه .

2020-09-05 05:49 UTC, hassanzaker commented on phase09/Learning/WeatherForecast.cs
> +    public class WeatherForecast
این کلاسو به گیت‌ایگنور اضافه کنین.
کلا فک کنم پوشه learning را به گیت‌ایگنور اضافه کنین.

2020-09-05 15:29 UTC, mahdimalverdi requested changes

2020-09-05 15:29 UTC, mahdimalverdi commented on phase09/Learning/Startup.cs
> +            services.AddTransient<IPerson,Student>();
چرا؟؟؟

2020-09-05 15:29 UTC, mahdimalverdi commented on phase09/Project/Controllers/SearchController.cs
> +            var search = new Search();
چرا از DI خونده نمیشه؟

2020-09-06 05:54 UTC, mahlashrifi commented on phase09/Learning/WeatherForecast.cs
> +    public class WeatherForecast
اضافه کردیم . منتها چون بعدش اضافه میشه گویا ایگنور نمیکنه . ممنون

2020-09-06 05:57 UTC, mahlashrifi commented on phase09/Learning/Startup.cs
> +            services.AddTransient<IPerson,Student>();
<div dir="rtl">این برای قسمت Learning هست . که به گیت ایگنور الان اضافش کردیم </div>

2020-09-06 05:59 UTC, mahlashrifi commented on phase09/Project/Controllers/SearchController.cs
> +            var search = new Search();
<div dir="rtl">منظورتون از ID چیه ؟</div>

2020-09-06 21:00 UTC, mahdimalverdi approved these changes

2020-09-07 12:26 UTC, hassanzaker approved these changes

2020-09-07 13:00 UTC, titansarus approved these changes

2020-09-09 14:10 UTC, mhgheisarieh approved these changes

2020-09-27 12:06 UTC, merged